### ISSUE TITLE
Парсинг DOCX: таблица

### ISSUE THREAD

**Issue by a-berezhkov** [normcontrol/normcontrol-Document-Parser#12]
Приведение таблица и ее свойств к единому классу

**Comment by algormx** [comment]
> Приведение таблица и ее свойств к единому классу

Непонятное описание.

**Comment by algormx** [comment]
> Приведение таблица и ее свойств к единому классу

Непонятно.

**Comment by algormx** [comment]
Это уже вроде как выполнено в #31. Стоит вопрос закрытия ишью.

**Comment by a-berezhkov** [comment]
> Это уже вроде как выполнено в #31. Стоит вопрос закрытия ишью.

Выполнено только для ODT формата.
