### ISSUE TITLE
Интеграция с классом src/Class/Paragraph.py 

### ISSUE THREAD

**Issue by a-berezhkov** [normcontrol/normcontrol-Document-Parser#16]
Сейчас  подключена локальная копия класса из `temp/Paragraph.py `
Подключить вместо нее вот эту `src/Class/Paragraph.py `
---
Now the local copy of the class from `temp/Paragraph.py` is included
Connect instead `src/Class/Paragraph.py `

**Comment by algormx** [comment]
> ## Сейчас подключена локальная копия класса из `temp/Paragraph.py `
> Подключить вместо нее вот эту `src/Class/Paragraph.py `
> 
> Now the local copy of the class from `temp/Paragraph.py` is included Connect instead `src/Class/Paragraph.py `

Что значит локальная копия?
