### ISSUE TITLE
Разделить DrawFrame на DrawFrame и Image

### ISSUE THREAD

**Issue by a-berezhkov** [normcontrol/normcontrol-Document-Parser#22]
В формате ODT есть понятие фрейме для картинок и других объектов.
Однако в остальных форматах его нет, поэтому необходимо разделить сущности.

**Comment by algormx** [comment]
> _No description provided._

Опишите в чем состоит необходимость.

**Comment by Vl-Tershch** [comment]
> > _No description provided._
> 
> Опишите в чем состоит необходимость. @Vl-Tershch

Как написал @a-berezhkov выше, в других форматах может отсутствовать возможность/необходимость хранить данные фрейма. Дополнительно, мы полагаем, логичнее разделить единую сущность на два объекта, которыми они фактически и являются.
