### ISSUE TITLE
Параметр attr_name лучше переимновать в style_attr_name. И название метода соответственно

### ISSUE THREAD

**Issue by a-berezhkov** [normcontrol/normcontrol-Document-Parser#25]
Параметр attr_name лучше переимновать в style_attr_name. И название метода соответственно

_Originally posted by @algormx in https://github.com/normcontrol/normcontrol-Document-Parser/pull/7#discussion_r1111322556_

**Comment by algormx** [comment]
> ```
>           Параметр attr_name лучше переимновать в style_attr_name. И название метода соответственно
> ```
> 
> _Originally posted by @algormx in [#7 (comment)](https://github.com/normcontrol/normcontrol-Document-Parser/pull/7#discussion_r1111322556)_

Не тянет на ишью.
