### ISSUE TITLE
Extend and restructure readme

### ISSUE THREAD

**Issue by arxiom** [normcontrol/normcontrol-Document-Parser#61]
И для этого предлагается полагаться на [следующую](https://github.com/aimclub/open-source-ops/blob/master/templates/template_README.md) структуру.

**Comment by algormx** [comment]
P.S. Не обязательно закончить все, но хотя бы выкатить первую версию.

**Comment by slavamarcin** [comment]
Окей, в ближайшее время всё сделаем
